SATAXI_IMPACT_FUND: "SA Taxi Impact Fund (RF) (Pty) Ltd is a registered Developmental Credit Provider: NCRCP8156 Reg. No.2012/093936/07"
SATAXI_SECURITISATION: "SA Taxi Securitisation (Pty) Ltd is a registered Developmental Credit Provider: NCRCP2617 Reg. No.2005/021852/07"
SATAXI_DEV_FINANCE: "SA Taxi Development Finance (Pty) Ltd is a registered Developmental Credit Provider: NCRCP4754 Reg. No. 2008/012599/07-"
TRANSFLOW_PTY_LTD: "Transflow (RF)(Pty) Ltd is a registered Developmental Credit Provider: NCRCP12313 Reg. No. 2018/631811/07"
TRANSSEC: "Transsec (RF) Ltd is a registered Developmental Credit Provider: NCRCP7932 Reg. No. 2012209822/06"
TRANSSEC2: "Transsec 2 (RF) Ltd is a registered Developmental Credit Provider: NCRCP7933 Reg. No. 2014/209982/06"
TRANSSEC3: "Transsec 3 (RF) Ltd is a registered Developmental Credit Provider: NCRCP9996 Reg. No. 2016/117311/06"
TRANSSEC4: "Transsec 4 (RF) Ltd is a registered Developmental Credit Provider: NCRCP12312 Reg. No. 2018/268776/06"
TRANSSEC5: "Transsec 5 (RF) Ltd is a registered Developmental Credit Provider: NCRCP14785 Reg. No. 2020/886422/06"
POTPALE_INVESTMENTS: "Potpale Investments (RF) (Pty) Ltd is a registered Developmental Credit Provider: NCRCP6238 Reg. No. 2011/118165/07"
SATAXI_FINANCE_SOLUTION: "SA Taxi Finance Solutions (RF) (Pty) Ltd is a registered Developmental Credit Provider: NCRCP4373 Reg.No. 2003/029687/07"
