CREATE TABLE finance.Agreement
( agreementID int generated by default as identity
, description varchar(100)
);

ALTER TABLE finance.Agreement ALTER agreementID SET NOT NULL;
ALTER TABLE finance.Agreement ALTER description SET NOT NULL;

ALTER TABLE finance.Agreement
 ADD CONSTRAINT AGREEMENT_PKEY PRIMARY KEY
  ( agreementID
  )
;

CREATE TABLE finance.Area
( areaID int generated by default as identity
, areaName varchar(100)
);

ALTER TABLE finance.Area ALTER areaID SET NOT NULL;
ALTER TABLE finance.Area ALTER areaName SET NOT NULL;

ALTER TABLE finance.Area
 ADD CONSTRAINT AREA_PKEY PRIMARY KEY
  ( areaID
  )
;

CREATE TABLE finance.ArticleType
( typeID int generated by default as identity
, type varchar(150)
);

ALTER TABLE finance.ArticleType ALTER typeID SET NOT NULL;
ALTER TABLE finance.ArticleType ALTER type SET NOT NULL;

ALTER TABLE finance.ArticleType
 ADD CONSTRAINT ARTICLETYPE_PKEY PRIMARY KEY
  ( typeID
  )
;


CREATE TABLE finance.Bank
( bankID int generated by default as identity
, bankName varchar(100)
);

ALTER TABLE finance.Bank ALTER bankID SET NOT NULL;
ALTER TABLE finance.Bank ALTER bankName SET NOT NULL;

ALTER TABLE finance.Bank
 ADD CONSTRAINT BANK_PKEY PRIMARY KEY
  ( bankID
  )
;

CREATE TABLE finance.ClientType
( clientTypeID int generated by default as identity
, type varchar(150)
);

ALTER TABLE finance.ClientType ALTER clientTypeID SET NOT NULL;
ALTER TABLE finance.ClientType ALTER type SET NOT NULL;

ALTER TABLE finance.ClientType
 ADD CONSTRAINT CLIENTTYPE_PKEY PRIMARY KEY
  ( clientTypeID
  )
;

CREATE TABLE finance.Country
( countryID int generated by default as identity
, countryName varchar(150)
);

ALTER TABLE finance.Country ALTER countryID SET NOT NULL;
ALTER TABLE finance.Country ALTER countryName SET NOT NULL;

ALTER TABLE finance.Country
 ADD CONSTRAINT COUNTRY_PKEY PRIMARY KEY
  ( countryID
  )
;

CREATE TABLE finance.DealerCode
( dealerCodeID int generated by default as identity
, dealerCode varchar(50)
);

ALTER TABLE finance.DealerCode ALTER dealerCodeID SET NOT NULL;
ALTER TABLE finance.DealerCode ALTER dealerCode SET NOT NULL;

ALTER TABLE finance.DealerCode
 ADD CONSTRAINT DEALERCODE_PKEY PRIMARY KEY
  ( dealerCodeID
  )
;

CREATE TABLE finance.InsuranceCompany
( companyID int generated by default as identity
, companyName varchar(100)
);

ALTER TABLE finance.InsuranceCompany ALTER companyID SET NOT NULL;
ALTER TABLE finance.InsuranceCompany ALTER companyName SET NOT NULL;

ALTER TABLE finance.InsuranceCompany
 ADD CONSTRAINT INSURANCECOMPANY_PKEY PRIMARY KEY
  ( companyID
  )
;

CREATE TABLE finance.Language
( languageID int generated by default as identity
, description varchar(100)
);

ALTER TABLE finance.Language ALTER languageID SET NOT NULL;
ALTER TABLE finance.Language ALTER description SET NOT NULL;

ALTER TABLE finance.Language
 ADD CONSTRAINT LANGUAGE_PKEY PRIMARY KEY
  ( languageID
  )
;

CREATE TABLE finance.Occupation
( occupationID int generated by default as identity
, occupation varchar(100)
);

ALTER TABLE finance.Occupation ALTER occupationID SET NOT NULL;
ALTER TABLE finance.Occupation ALTER occupation SET NOT NULL;

ALTER TABLE finance.Occupation
 ADD CONSTRAINT OCCUPATION_PKEY PRIMARY KEY
  ( occupationID
  )
;

CREATE TABLE finance.Relation
( relativeID int generated by default as identity
, relative varchar(100)
);

ALTER TABLE finance.Relation ALTER relativeID SET NOT NULL;
ALTER TABLE finance.Relation ALTER relative SET NOT NULL;

ALTER TABLE finance.Relation
 ADD CONSTRAINT RELATION_PKEY PRIMARY KEY
  ( relativeID
  )
;

CREATE TABLE finance.TypeOfSale
( typeOfSaleID int generated by default as identity
, type varchar(50)
);

ALTER TABLE finance.TypeOfSale ALTER typeOfSaleID SET NOT NULL;
ALTER TABLE finance.TypeOfSale ALTER type SET NOT NULL;

ALTER TABLE finance.TypeOfSale
 ADD CONSTRAINT TYPEOFSALE_PKEY PRIMARY KEY
  ( typeOfSaleID
  )
;

CREATE TABLE finance.EmployerIndustryType
( industryTypeID int generated by default as identity
, type varchar(100)
);

ALTER TABLE finance.EmployerIndustryType ALTER industryTypeID SET NOT NULL;
ALTER TABLE finance.EmployerIndustryType ALTER type SET NOT NULL;

ALTER TABLE finance.EmployerIndustryType
 ADD CONSTRAINT EMPLOYERINDUSTRYTYPE_PKEY PRIMARY KEY
  ( industryTypeID
  )
;

CREATE TABLE finance.InsuranceBroker
( brokerID int generated by default as identity
, brokerName varchar(100)
);

ALTER TABLE finance.InsuranceBroker ALTER brokerID SET NOT NULL;
ALTER TABLE finance.InsuranceBroker ALTER brokerName SET NOT NULL;

ALTER TABLE finance.InsuranceBroker
 ADD CONSTRAINT INSURANCEBROKER_PKEY PRIMARY KEY
  ( brokerID
  )
;
